/**
 * Verify that the TypeScript engine matches the Python engine on the recorded
 * fixtures (generated by scripts/make_fixture.py).
 *
 * Usage: node --experimental-strip-types scripts/test-engine.mjs
 */

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { analyzeWithModel, InputError } from '../lib/sentiment.ts';

const root = fileURLToPath(new URL('..', import.meta.url));
const model = JSON.parse(readFileSync(`${root}public/model.json`, 'utf8'));
const fixtures = JSON.parse(readFileSync(`${root}scripts/fixtures.json`, 'utf8'));

let failures = 0;
const check = (condition, message) => {
  if (!condition) {
    failures += 1;
    console.error(`FAIL: ${message}`);
  }
};

check(fixtures.length === 41, `expected 41 fixtures, found ${fixtures.length}`);

for (const fixture of fixtures) {
  const result = analyzeWithModel(fixture.text, model);
  check(
    JSON.stringify(result.tokens) === JSON.stringify(fixture.tokens),
    `tokens differ for ${JSON.stringify(fixture.text)}: ${JSON.stringify(result.tokens)} vs ${JSON.stringify(fixture.tokens)}`
  );
  check(
    result.label === fixture.label,
    `label differs for ${JSON.stringify(fixture.text)}: ${result.label} vs ${fixture.label}`
  );
  check(
    result.insufficient === fixture.insufficient,
    `insufficient flag differs for ${JSON.stringify(fixture.text)}`
  );
  for (const label of ['positive', 'neutral', 'negative']) {
    const delta = Math.abs(result.probabilities[label] - fixture.probabilities[label]);
    check(delta <= 1e-6, `probability ${label} differs by ${delta} for ${JSON.stringify(fixture.text)}`);
  }
}

let threw = false;
try {
  analyzeWithModel('   ', model);
} catch (error) {
  threw = error instanceof InputError;
}
check(threw, 'blank text should throw InputError');

if (failures > 0) {
  console.error(`${failures} failure(s).`);
  process.exit(1);
}
console.log(`OK: 41 inputs match between Python and TypeScript.`);
